
<div class="row">
    <div class="col-md-6"><h1>Contact list</h1></div>
    <div class="col-md-6">
        <a href="<?= $block->getAddUrl(); ?>" class="action create primary"><span>New Contact</span></a>
    </div>
</div>


<?php
$srno = 1;
$collection = $block->getPostData();
    echo "<table>";
    echo "<tr>";
    echo "<td>Id</td>";
    echo "<td>Name</td>";
    echo "<td>Content</td>";
    echo "<td>Mobile</td>";
    echo "<td>Status</td>";
    echo "<td>Image</td>";
    echo "<td>Action</td>";
    echo "</tr>";    
    foreach($collection as $item){
        echo "<tr>";
        echo "<td>".$srno."</td>";
        echo "<td>".$item['name']."</td>";
        echo "<td>".$item['content']."</td>";
        echo "<td>".$item['mobile']."</td>";
        echo "<td>".$item['status']."</td>"; ?>
        <td><img src="<?php echo $block->getMediaPath();?>/<?php echo $item['image'];?>" style="width:60px; min-height:60px;" /></td>
        <?php  echo "<td><a href='".$block->getEditUrl($item['id'])."'>Edit</a> &nbsp;<a href='".$block->getDeleteUrl($item['id'])."'>Delete</a></td>";
            echo "</tr>";

        $srno++;
    }
    echo "</table>";
?>

